flowchart TD
  A2[P2: Forzar?] -->|Sí| F2[P1: Oferta forzada]
  A2 -->|No| B2[P1: Ofrecer 5?]
  F2 --> C2[P2: Acción final]
  B2 -->|No ofrecer| O1[10,10]
  B2 -->|Ofrecer| C2[P2: Aceptar / Rechazar / Robar]
  C2 -->|Aceptar| O2[15,15]
  C2 -->|Rechazar| O3[10,10]
  C2 -->|Robar| O4[5,20]
