flowchart TD
  A3[P1: Proponer oferta?] -->|No ofrecer| O1[Sin cambios]
  A3 -->|Ofrecer| B3[P2: Aceptar / Rechazar / Robar]
  B3 -->|Aceptar| O2[Intercambiar según oferta/pedido]
  B3 -->|Rechazar| O3[Sin cambios]
  B3 -->|Robar| C3[P1: Asignar ficha de vergüenza?]
  C3 -->|Sí| O4a[+1 vergüenza para P2]
  C3 -->|No| O4b[Sin vergüenza]
