flowchart TD
  A4[P1: Ofrecer 5?] -->|No ofrecer| O1[10,10]
  A4 -->|Ofrecer| B4[P2: Aceptar / Rechazar / Robar]
  B4 -->|Aceptar| O2[15,15]
  B4 -->|Rechazar| O3[10,10]
  B4 -->|Robar| C4[P1: ¿Denunciar?]
  C4 -->|No| O4[5,20]
  C4 -->|Sí| J4[AutoJudge confisca tokens P2]
  J4 --> O5[10,0]
